# Generated by Django 5.1.4 on 2025-01-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/images/"),
        ),
    ]
